#!/usr/bin/env python3
"""Append an illustrated 'image compendium' appendix to a book's BOOK.md, for the EPUB/PDF.

Each book's design/IMAGE_COMPENDIUM.md is a curated set of freely-licensed Wikimedia images
(public-domain / CC) with captions, sources and required credit lines, and the image files live
in design/images/. Those images already illustrate the web Place Wiki; this bundles them into the
downloadable book as back matter so the EPUB and PDF are illustrated too.

What it emits (back matter, after the last chapter):

    ## Image Compendium — <book title>

    <short licence/attribution preamble>

    ### <section name, e.g. "Places of awe">
    ![caption](/abs/path/to/image.jpg)
    *caption*
    <small>Photographer, Licence, via Wikimedia Commons</small>
    ...

Design notes:
  · Image paths are rewritten to ABSOLUTE paths — pandoc/tectonic in render_book.sh run without a
    --resource-path, so relative paths (resolved from cwd) are unreliable (same reason the route-map
    frontispiece uses an absolute path).
  · Credits go UNDER each image (the per-image caption form), as chosen.
  · Idempotent: a sentinel comment brackets the injected block, so re-running replaces it rather
    than stacking duplicates. Safe to run on every build.
  · Pure stdlib, deterministic, offline.

Usage:
    python3 tools/inject_image_appendix.py <book-dir>        # e.g. books/the-sheltering-desert
    python3 tools/inject_image_appendix.py --all             # every book that has a compendium
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Appendix images are downsized into build/appendix-images/ so the source files (shared with the
# web Place Wiki) stay pristine and the EPUB/PDF stay lean. ~1400px wide is ample for screen/print.
MAX_W = 1400
JPEG_Q = 82


def _downsized(src: Path, cache_dir: Path) -> Path:
    """Return a path to a width-capped JPEG copy of src in cache_dir (built on demand). Falls back
    to the original if Pillow is unavailable or the image is already small."""
    try:
        from PIL import Image
    except ImportError:
        return src
    cache_dir.mkdir(parents=True, exist_ok=True)
    out = cache_dir / (src.stem + ".jpg")
    try:
        im = Image.open(src)
        if im.width <= MAX_W and src.suffix.lower() in (".jpg", ".jpeg"):
            return src  # already small enough; use as-is
        im = im.convert("RGB")
        if im.width > MAX_W:
            im = im.resize((MAX_W, round(im.height * MAX_W / im.width)), Image.LANCZOS)
        im.save(out, "JPEG", quality=JPEG_Q, optimize=True)
        return out
    except Exception:
        return src

BEGIN = "<!-- BEGIN image-compendium-appendix (generated by tools/inject_image_appendix.py) -->"
END = "<!-- END image-compendium-appendix -->"

# Markdown patterns in a compendium
RE_SECTION = re.compile(r"^##\s+(?!#)(.+?)\s*$")          # "## Places of awe" (not ###)
RE_CAPTION = re.compile(r"^###\s+(.+?)\s*$")               # "### The Kuiseb canyon — ..."
RE_IMAGE = re.compile(r"^!\[[^\]]*\]\(([^)]+)\)\s*$")      # "![alt](design/images/x.jpg)"
RE_CREDIT = re.compile(r"^-\s+\*\*Credit line[^:]*:\*\*\s*(.+?)\s*$")


def _book_title(book_dir: Path) -> str:
    """Best-effort book title for the appendix heading: BOOK.md H1 → compendium H1 → folder name."""
    book_md = book_dir / "build" / "BOOK.md"
    if book_md.exists():
        for line in book_md.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip().strip("*")
    comp = book_dir / "design" / "IMAGE_COMPENDIUM.md"
    if comp.exists():
        first = comp.read_text(encoding="utf-8").splitlines()[0]
        # "# Image Compendium — The Indifferent Desert (the Namib — ...)" → "The Indifferent Desert"
        m = re.match(r"#\s+Image Compendium\s+—\s+(.+?)(?:\s+\(|$)", first)
        if m:
            return m.group(1).strip()
    return book_dir.name.replace("-", " ").title()


def build_appendix(book_dir: Path) -> str | None:
    """Render the appendix markdown for one book, or None if it has no usable compendium."""
    comp = book_dir / "design" / "IMAGE_COMPENDIUM.md"
    if not comp.exists():
        return None
    img_root = book_dir / "design"  # image paths in the compendium are relative to design/'s parent
    cache_dir = book_dir / "build" / "appendix-images"
    lines = comp.read_text(encoding="utf-8").splitlines()

    out: list[str] = [
        f"## Image Compendium — {_book_title(book_dir)}",
        "",
        "The places, peoples, and wonders in this book are real. These freely-licensed photographs "
        "(public domain or Creative Commons, via Wikimedia Commons) are gathered here so you can see "
        "them — go stand in them. Each image carries its photographer and licence.",
        "",
    ]

    pending_caption: str | None = None
    pending_image: str | None = None
    n_images = 0

    def flush(credit: str | None) -> None:
        nonlocal pending_caption, pending_image, n_images
        if pending_image is None:
            return
        # Resolve to an absolute path (render gate has no --resource-path).
        rel = pending_image
        abs_path = (book_dir / rel).resolve() if not rel.startswith("design/") else (img_root.parent / rel).resolve()
        if not abs_path.exists():
            # skip silently-missing files but keep going
            pending_caption, pending_image = None, None
            return
        abs_path = _downsized(abs_path, cache_dir)  # width-capped copy keeps the book lean
        cap = (pending_caption or "").strip()
        out.append(f"![{cap}]({abs_path})")
        out.append("")
        if cap:
            out.append(f"*{cap}*")
        if credit:
            out.append(f"<small>{credit.strip()}</small>")
        out.append("")
        n_images += 1
        pending_caption, pending_image = None, None

    for ln in lines:
        m_sec = RE_SECTION.match(ln)
        m_cap = RE_CAPTION.match(ln)
        m_img = RE_IMAGE.match(ln)
        m_cred = RE_CREDIT.match(ln)
        if m_sec:
            flush(None)
            # skip the compendium's own title line ("Image Compendium — ...")
            if not m_sec.group(1).lower().startswith("image compendium"):
                out.extend([f"### {m_sec.group(1)}", ""])
        elif m_cap:
            flush(None)
            pending_caption = m_cap.group(1)
        elif m_img:
            pending_image = m_img.group(1)
        elif m_cred:
            flush(m_cred.group(1))
    flush(None)

    if n_images == 0:
        return None
    return "\n".join(out).rstrip() + "\n"


def inject(book_dir: Path) -> bool:
    """Inject (or refresh) the appendix into book_dir/build/BOOK.md. Returns True if written."""
    book_md = book_dir / "build" / "BOOK.md"
    if not book_md.exists():
        print(f"  [skip] {book_dir.name}: no build/BOOK.md (merge first)")
        return False
    appendix = build_appendix(book_dir)
    if appendix is None:
        print(f"  [skip] {book_dir.name}: no usable image compendium")
        return False

    text = book_md.read_text(encoding="utf-8")
    # strip any prior injected block (idempotent)
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S).rstrip()

    block = f"\n\n---\n\n{BEGIN}\n\n{appendix}\n{END}\n"
    book_md.write_text(text + block + "\n", encoding="utf-8")
    n = appendix.count("![")
    print(f"  [ok] {book_dir.name}: appended {n} image(s) to BOOK.md")
    return True


def all_compendium_books() -> list[Path]:
    return sorted({p.parent.parent for p in REPO.glob("books/**/design/IMAGE_COMPENDIUM.md")})


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    if argv[0] == "--all":
        books = all_compendium_books()
        print(f"injecting image appendix into {len(books)} book(s):")
        for b in books:
            inject(b)
        return 0
    book_dir = (REPO / argv[0]).resolve() if not Path(argv[0]).is_absolute() else Path(argv[0])
    return 0 if inject(book_dir) else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
