"""Language-specific translation tables for SA urban + Swahili corpus expansion."""

from __future__ import annotations

# isiZulu — KZN/Gauteng urban + garage register
ZU: dict[str, str] = {
    "Hello there": "Sawubona mfowethu",
    "How are you?": "Unjani?",
    "That's great": "Kuhle kakhulu",
    "Nice one": "Sharp sharp",
    "Yes, exactly": "Yebo, kahle",
    "Brother": "Bhuti",
    "In a little while": "Kancane nje",
    "Get lost": "Sukuma",
    "What a pity": "Eish, njalo",
    "Really?": "Ngempela?",
    "cubbyhole": "ibhokisi le-dashboard",
    "glove compartment": "ibhokisi le-dashboard",
    "glove box": "ibhokisi le-dashboard",
    "windshield wipers": "ama-wiper ewindscreen",
    "windscreen wipers": "ama-wiper ewindscreen",
    "piston": "ipiston",
    "pistons": "amapiston",
    "brakes": "amabreki",
    "brake": "ibhreki",
    "engine": "injini",
    "the engine": "injini",
    "internal combustion": "ukushiswa kwangaphakathi",
    "crankshaft": "i-crankshaft",
    "connecting rod": "i-connecting rod",
    "cylinder": "isilinda",
    "cylinders": "izilinda",
    "four-stroke cycle": "ukuphila kwe-four-stroke",
    "transmission": "igearbox",
    "gearbox": "igearbox",
    "manual transmission": "igearbox yamanually",
    "automatic transmission": "i-auto gearbox",
    "clutch": "i-clutch",
    "gear lever": "i-gear lever",
    "gear stick": "i-gear stick",
    "brake system": "uhlelo lwamabreki",
    "brake pedal": "ipepedi lebhreki",
    "handbrake": "i-handbrake",
    "parking brake": "i-handbrake",
    "hydraulic fluid": "ichwezi le-hydraulic",
    "brake calipers": "ama-caliper ebhreki",
    "calipers": "ama-caliper",
    "wheel cylinders": "ama-cylinder ewheel",
    "brake discs": "amadiski ebhreki",
    "discs": "amadiski",
    "brake drums": "amadrum ebhreki",
    "drums": "amadrum",
    "anti-lock system": "i-ABS system",
    "ABS": "i-ABS",
    "steering": "ukulawula",
    "steering wheel": "i-steering wheel",
    "steering rack": "i-steering rack",
    "power steering": "i-power steering",
    "suspension": "ukuphakama",
    "springs": "amaspring",
    "shock absorbers": "ama-shock absorber",
    "struts": "ama-strut",
    "battery": "ibhethri",
    "car battery": "ibhethri yemoto",
    "alternator": "i-alternator",
    "fan belt": "ibhande lefan",
    "drive belt": "ibhande lokushayela",
    "radiator": "iradiyetha",
    "coolant": "ichwezi lokupholisa",
    "thermostat": "i-thermostat",
    "overheating": "ukushisa kakhulu",
    "exhaust": "umkhuhlane",
    "exhaust pipe": "ipayipi lomkhuhlane",
    "catalytic converter": "i-catalytic converter",
    "muffler": "isilencer",
    "tailpipe": "ipayipi lomkhuhlane",
    "wheels": "amavili",
    "tyres": "amathayi",
    "tires": "amathayi",
    "tyre pressure": "ingcindezi yethayi",
    "spare wheel": "iwheel yokunakekela",
    "spare tyre": "ithayi yokunakekela",
    "fuel tank": "itanki yepetrol",
    "petrol tank": "itanki yepetrol",
    "petrol": "ipetrol",
    "diesel": "idiesel",
    "fuel pump": "ipampu yepetrol",
    "fuel filter": "isihlungi sepetrol",
    "fuel gauge": "igeyiji yepetrol",
    "dashboard": "idashboard",
    "speedometer": "isivinini",
    "tachometer": "i-tachometer",
    "rev counter": "i-rev counter",
    "warning lamps": "izibani zesixwayiso",
    "warning lights": "ama-warning light",
    "oil pressure": "ingcindezi yewoyela",
    "low oil pressure": "ingcindezi yewoyela ephansi",
    "oil filter": "isihlungi sewoyela",
    "engine oil": "iwoyela lenjini",
    "drivetrain": "uhlelo lokushayela",
    "torque": "i-torque",
    "revolutions per minute": "amajuba ngomzuzu",
    "RPM": "i-RPM",
    "refuelling": "ukugcwalisa ipetrol",
    "petrol station": "igesi",
    "garage": "igaraji",
    "workshop": "i-workshop",
    "mechanic": "umshini wemoto",
    "panel beater": "umshini we-panel",
    "breakdown": "ukuphuka kwemoto",
    "car broke down": "imoto yaphuka",
    "tow-in": "ukudonsela",
    "tow truck": "ilori yokudonsela",
    "bonnet": "idekseli lenjini",
    "hood": "idekseli lenjini",
    "boot": "itrunk",
    "trunk": "itrunk",
    "indicators": "ama-indicator",
    "turn signals": "ama-indicator",
    "headlights": "izibani zangaphambili",
    "headlamps": "izibani zangaphambili",
    "fog lights": "izibani zenkungu",
    "rearview mirror": "isibuko sangemuva",
    "side mirror": "isibuko esihlangothini",
    "windscreen": "iwindscreen",
    "carburettor": "i-carburettor",
    "carburetor": "i-carburetor",
    "spark plugs": "ama-spark plug",
    "ignition": "ukuvutha",
    "air filter": "isihlungi somoya",
    "air conditioning": "i-aircon",
    "aircon": "i-aircon",
    "hub": "ihub",
    "axle": "i-axle",
    "wheel hub": "ihub yewheel",
    "passenger car": "imoto yabantu",
    "car": "imoto",
    "motor car": "imoto",
    "centre console": "i-centre console",
    "cup holder": "isibambi sekhompu",
    "seat belt": "ibhande lokuhlala",
    "seatbelt": "ibhande lokuhlala",
    "hazard lights": "izibani zesixwayiso",
    "hooter": "ihooter",
    "horn": "ihooter",
    "pedals": "amapedali",
    "accelerator": "i-accelerator",
    "accelerator pedal": "ipepedi le-accelerator",
    "footwell": "indawo yezinyawo",
    "sun visor": "i-sun visor",
    "rear seat": "isihlalo sangemuva",
    "front seat": "isihlalo sangaphambili",
    "back seat": "isihlalo sangemuva",
    "infotainment": "i-infotainment",
    "car radio": "irediyo yemoto",
    "car stereo": "i-stereo yemoto",
    "key fob": "i-key fob",
    "ignition key": "likhi lokuvutha",
    "steering column": "ikholomu ye-steering",
    "floor mat": "icarpet phansi",
    "ashtray": "isitsha sasigwayi",
    "odometer": "i-odometer",
    "trip meter": "i-trip meter",
    "traffic light": "i-robot",
    "traffic lights": "ama-robot",
    "pickup truck": "ibakkie",
    "pick-up": "ibakkie",
    "ute": "ibakkie",
    "minibus taxi": "itekisi",
    "taxi rank": "irank yamatekisi",
    "road": "umgwaqo",
    "the road": "umgwaqo",
    "highway": "uhighway",
    "freeway": "uhighway",
    "just now": "muva nje",
    "now now": "manje manje",
    "later": "kamuva",
    "is it?": "ke?",
    "isn't it?": "ke?",
    "sharp": "sharp",
    "cool": "kuhle",
    "awesome": "kuhle kakhulu",
    "mate": "mfowethu",
    "dude": "bhuti",
    "hey": "heyi",
    "what's up": "kunjani?",
    "ag shame": "eish",
    "shame": "eish",
    "braai": "ibraai",
    "barbecue": "ibraai",
    "sosatie": "isosati",
    "jol": "ukujola",
    "party": "ipati",
    "eish": "eish",
    "yoh": "yoh",
    "ja nee": "yebo cha",
    "yes no": "yebo cha",
    "no ways": "cha nje",
    "shot": "ngiyabonga",
    "thanks": "ngiyabonga",
    "thank you": "ngiyabonga",
    "please": "ngicela",
    "sorry": "uxolo",
    "excuse me": "ngicela uxolo",
    "township": "ilokishi",
    "suburb": "isuburb",
    "flat": "ifulethi",
    "apartment": "ifulethi",
    "cellphone": "icellphone",
    "mobile phone": "icellphone",
    "load shedding": "ukushenxa ugesi",
    "power cut": "ukuphela kogesi",
    "robot": "i-robot",
    "cheers": "phansi",
    "drink": "ukuphuza",
    "hangover": "isibhozo",
    "hang out": "ukuhlangana",
    "chill": "ukuphumula",
    "student": "umfundi",
    "campus": "ikampasi",
    "lecture": "isifundo",
    "exam": "i-exam",
    "test": "i-test",
    "Gauteng": "iGauteng",
    "Cape Town": "iKapa",
    "Joburg": "iJoburg",
    "Johannesburg": "iJohannesburg",
    "Durban": "iTheku",
    "Pretoria": "iPitoli",
    "my china": "china yami",
    "china": "china",
    "bru": "bhuti",
    "cuz": "mfwethu",
    "cousin": "umzala",
    "auntie": "umamkhulu",
    "uncle": "umalume",
    "grandmother": "ugogo",
    "grandfather": "umkhulu",
    "now": "manje",
    "quick": "ngokushesha",
    "fast": "ngokushesha",
    "slow": "kancane",
    "stop": "yima",
    "go": "hamba",
    "wait": "linda",
    "hurry": "shesha",
    "money": "imali",
    "cash": "imali",
    "expensive": "kubiza",
    "cheap": "kushibhile",
    "food": "ukudla",
    "takeaway": "i-takeaway",
    "takeaways": "ama-takeaway",
    "Pistons and Crankshaft": "Amapiston ne-Crankshaft",
    "Brakes": "Amabreki",
    "faults": "izinkinga",
    "Engine": "Injini",
    "Transmission": "Igearbox",
    "Steering": "Ukulawula",
    "Suspension": "Ukuphakama",
    "Battery and Alternator": "Ibhethri ne-Alternator",
    "Radiator and Cooling": "Iradiyetha nokupholisa",
    "Exhaust": "Umkhuhlane",
    "Wheels and Tyres": "Amavili namathayi",
    "Fuel Tank": "Itanki yepetrol",
    "Dashboard Instruments": "Amamethri edashboard",
    "Windscreen Wipers and Cabin Storage": "Ama-wiper nebhokisi le-dashboard",
    "indicate faults such as": "bonisa izinkinga ezifana ne",
}

# isiXhosa — Cape/Eastern Cape urban + garage register
XH: dict[str, str] = {
    "Hello there": "Molo bhuti",
    "How are you?": "Unjani?",
    "That's great": "Kuhle kakhulu",
    "Nice one": "Sharp",
    "Yes, exactly": "Ewe, ngqo",
    "Brother": "Bhuti",
    "In a little while": "Kancinci",
    "Get lost": "Hamba",
    "What a pity": "Eish, nje",
    "Really?": "Ngokwenene?",
    "cubbyhole": "ibhokisi le-dashboard",
    "glove compartment": "ibhokisi le-dashboard",
    "glove box": "ibhokisi le-dashboard",
    "windshield wipers": "ama-wiper",
    "windscreen wipers": "ama-wiper",
    "piston": "ipiston",
    "pistons": "amapiston",
    "brakes": "iibhreki",
    "brake": "ibhreki",
    "engine": "injini",
    "the engine": "injini",
    "internal combustion": "ukutshiswa kwangaphakathi",
    "crankshaft": "i-crankshaft",
    "connecting rod": "i-connecting rod",
    "cylinder": "isilinda",
    "cylinders": "iisilinda",
    "four-stroke cycle": "i-four-stroke cycle",
    "transmission": "igearbox",
    "gearbox": "igearbox",
    "manual transmission": "igearbox yamanually",
    "automatic transmission": "i-auto gearbox",
    "clutch": "i-clutch",
    "gear lever": "i-gear lever",
    "gear stick": "i-gear stick",
    "brake system": "inkqubo yeebhreki",
    "brake pedal": "iphedali yebrake",
    "handbrake": "i-handbrake",
    "parking brake": "i-handbrake",
    "hydraulic fluid": "ilungelo le-hydraulic",
    "brake calipers": "iicaliper zebrake",
    "calipers": "iicaliper",
    "wheel cylinders": "iicylinder zewheel",
    "brake discs": "iidiski zebrake",
    "discs": "iidiski",
    "brake drums": "iidrums zebrake",
    "drums": "iidrums",
    "anti-lock system": "i-ABS system",
    "ABS": "i-ABS",
    "steering": "ukulawula",
    "steering wheel": "i-steering wheel",
    "steering rack": "i-steering rack",
    "power steering": "i-power steering",
    "suspension": "ukunyuswa",
    "springs": "iispring",
    "shock absorbers": "iishock absorber",
    "struts": "iistrut",
    "battery": "ibhetri",
    "car battery": "ibhetri yemoto",
    "alternator": "i-alternator",
    "fan belt": "ibelt yefan",
    "drive belt": "ibelt yokushayela",
    "radiator": "iradiyetha",
    "coolant": "ilungelo lokupholisa",
    "thermostat": "i-thermostat",
    "overheating": "ukushisa kakhulu",
    "exhaust": "umkhuhlane",
    "exhaust pipe": "ityubo lomkhuhlane",
    "catalytic converter": "i-catalytic converter",
    "muffler": "isilencer",
    "tailpipe": "ityubo lomkhuhlane",
    "wheels": "iivili",
    "tyres": "amatyre",
    "tires": "amatyre",
    "tyre pressure": "uxinzelelo lwetyre",
    "spare wheel": "iwheel yokugqibela",
    "spare tyre": "ityre yokugqibela",
    "fuel tank": "itanki yepetrol",
    "petrol tank": "itanki yepetrol",
    "petrol": "ipetrol",
    "diesel": "idiesel",
    "fuel pump": "ipump yepetrol",
    "fuel filter": "isihluzi sepetrol",
    "fuel gauge": "igeyiji yepetrol",
    "dashboard": "idashboard",
    "speedometer": "isivinini",
    "tachometer": "i-tachometer",
    "rev counter": "i-rev counter",
    "warning lamps": "iilights zesilumkiso",
    "warning lights": "iilights zesilumkiso",
    "oil pressure": "uxinzelelo lwayoli",
    "low oil pressure": "uxinzelelo lwayoli luphantsi",
    "oil filter": "isihluzi sayoli",
    "engine oil": "ioli yeinjini",
    "drivetrain": "inkqubo yokushayela",
    "torque": "i-torque",
    "revolutions per minute": "i-RPM",
    "RPM": "i-RPM",
    "refuelling": "ukuzalisa ipetrol",
    "petrol station": "igesi",
    "garage": "igaraji",
    "workshop": "i-workshop",
    "mechanic": "umqhubi wemoto",
    "panel beater": "umqhubi we-panel",
    "breakdown": "ukuphuka kwemoto",
    "car broke down": "imoto yaphuka",
    "tow-in": "ukudonsela",
    "tow truck": "ilori yokudonsela",
    "bonnet": "idekseli yeinjini",
    "hood": "idekseli yeinjini",
    "boot": "itrunk",
    "trunk": "itrunk",
    "indicators": "ama-indicator",
    "turn signals": "ama-indicator",
    "headlights": "iilights zangaphambili",
    "headlamps": "iilights zangaphambili",
    "fog lights": "iilights zenkungu",
    "rearview mirror": "isibuko sangemva",
    "side mirror": "isibuko esicaleni",
    "windscreen": "iwindscreen",
    "carburettor": "i-carburettor",
    "carburetor": "i-carburetor",
    "spark plugs": "iispark plug",
    "ignition": "ukuvutha",
    "air filter": "isihluzi somoya",
    "air conditioning": "i-aircon",
    "aircon": "i-aircon",
    "hub": "ihub",
    "axle": "i-axle",
    "wheel hub": "ihub yewheel",
    "passenger car": "imoto yabantu",
    "car": "imoto",
    "motor car": "imoto",
    "centre console": "i-centre console",
    "cup holder": "isibambi sekompu",
    "seat belt": "ibelt yokuhlala",
    "seatbelt": "ibelt yokuhlala",
    "hazard lights": "iilights zesilumkiso",
    "hooter": "ihooter",
    "horn": "ihooter",
    "pedals": "iiphedali",
    "accelerator": "i-accelerator",
    "accelerator pedal": "iphedali ye-accelerator",
    "footwell": "indawo yeenyawo",
    "sun visor": "i-sun visor",
    "rear seat": "isihlalo sangemva",
    "front seat": "isihlalo sangaphambili",
    "back seat": "isihlalo sangemva",
    "infotainment": "i-infotainment",
    "car radio": "irediyo yemoto",
    "car stereo": "i-stereo yemoto",
    "key fob": "i-key fob",
    "ignition key": "likhi lokuvutha",
    "steering column": "ikholomu ye-steering",
    "floor mat": "icarpet phantsi",
    "ashtray": "isitya sasigwayi",
    "odometer": "i-odometer",
    "trip meter": "i-trip meter",
    "traffic light": "i-robot",
    "traffic lights": "ama-robot",
    "pickup truck": "ibakkie",
    "pick-up": "ibakkie",
    "ute": "ibakkie",
    "minibus taxi": "itekisi",
    "taxi rank": "irank yamatekisi",
    "road": "umgwaqo",
    "the road": "umgwaqo",
    "highway": "uhighway",
    "freeway": "uhighway",
    "just now": "ngoku nje",
    "now now": "ngoku ngoku",
    "later": "kamva",
    "is it?": "ke?",
    "isn't it?": "ke?",
    "sharp": "sharp",
    "cool": "kuhle",
    "awesome": "kuhle kakhulu",
    "mate": "mhlobo wam",
    "dude": "bhuti",
    "hey": "heyi",
    "what's up": "kunjani?",
    "ag shame": "eish",
    "shame": "eish",
    "braai": "ibraai",
    "barbecue": "ibraai",
    "sosatie": "isosati",
    "jol": "ukujola",
    "party": "ipati",
    "eish": "eish",
    "yoh": "yoh",
    "ja nee": "ewe hayi",
    "yes no": "ewe hayi",
    "no ways": "hayi nje",
    "shot": "enkosi",
    "thanks": "enkosi",
    "thank you": "enkosi",
    "please": "ngicela",
    "sorry": "uxolo",
    "excuse me": "ndicela uxolo",
    "township": "ilokishi",
    "suburb": "isuburb",
    "flat": "ifulethi",
    "apartment": "ifulethi",
    "cellphone": "icellphone",
    "mobile phone": "icellphone",
    "load shedding": "ukucinywa kogesi",
    "power cut": "ukuphela kogesi",
    "robot": "i-robot",
    "cheers": "phantsi",
    "drink": "ukusela",
    "hangover": "isibhozo",
    "hang out": "ukuhlangana",
    "chill": "ukuphumla",
    "student": "umfundi",
    "campus": "ikampasi",
    "lecture": "isifundo",
    "exam": "i-exam",
    "test": "i-test",
    "Gauteng": "iGauteng",
    "Cape Town": "iKapa",
    "Joburg": "iJoburg",
    "Johannesburg": "iJohannesburg",
    "Durban": "iTheku",
    "Pretoria": "iPitoli",
    "my china": "china yam",
    "china": "china",
    "bru": "bhuti",
    "cuz": "mzala",
    "cousin": "umzala",
    "auntie": "umamkhulu",
    "uncle": "umalume",
    "grandmother": "umakhulu",
    "grandfather": "umkhulu",
    "now": "ngoku",
    "quick": "ngokukhawuleza",
    "fast": "ngokukhawuleza",
    "slow": "kancinci",
    "stop": "yima",
    "go": "hamba",
    "wait": "linda",
    "hurry": "khawuleza",
    "money": "imali",
    "cash": "imali",
    "expensive": "kubiza",
    "cheap": "kushibhile",
    "food": "ukutya",
    "takeaway": "i-takeaway",
    "takeaways": "iitakeaway",
    "Pistons and Crankshaft": "Amapiston ne-Crankshaft",
    "Brakes": "Iibhreki",
    "faults": "iingxaki",
    "Engine": "Injini",
    "Transmission": "Igearbox",
    "Steering": "Ukulawula",
    "Suspension": "Ukunyuswa",
    "Battery and Alternator": "Ibhetri ne-Alternator",
    "Radiator and Cooling": "Iradiyetha nokupholisa",
    "Exhaust": "Umkhuhlane",
    "Wheels and Tyres": "Iivili namatyres",
    "Fuel Tank": "Itanki yepetrol",
    "Dashboard Instruments": "Iimethri zedashboard",
    "Windscreen Wipers and Cabin Storage": "Ama-wiper nebhokisi le-dashboard",
    "indicate faults such as": "bonisa iingxaki ezifana ne",
}

# Setswana — Gauteng/North West + Botswana overlap garage register
TN: dict[str, str] = {
    "Hello there": "Dumela rre",
    "How are you?": "O tsogile jang?",
    "That's great": "Go monate",
    "Nice one": "Sharp",
    "Yes, exactly": "Ee, tota",
    "Brother": "Rre",
    "In a little while": "Gangwe fela",
    "Get lost": "Tsamaya",
    "What a pity": "Eish, jalo",
    "Really?": "Ka nnete?",
    "cubbyhole": "lepono la dashboard",
    "glove compartment": "lepono la dashboard",
    "glove box": "lepono la dashboard",
    "windshield wipers": "ma-wiper",
    "windscreen wipers": "ma-wiper",
    "piston": "piston",
    "pistons": "dipiston",
    "brakes": "dibreki",
    "brake": "breeki",
    "engine": "enjini",
    "the engine": "enjini",
    "internal combustion": "go tshuba mo gare",
    "crankshaft": "crankshaft",
    "connecting rod": "connecting rod",
    "cylinder": "silinda",
    "cylinders": "disilinda",
    "four-stroke cycle": "four-stroke cycle",
    "transmission": "gearbox",
    "gearbox": "gearbox",
    "manual transmission": "gearbox ya seatla",
    "automatic transmission": "auto gearbox",
    "clutch": "clutch",
    "gear lever": "gear lever",
    "gear stick": "gear stick",
    "brake system": "tsamaiso ya dibreki",
    "brake pedal": "pedala ya breeki",
    "handbrake": "handbrake",
    "parking brake": "handbrake",
    "hydraulic fluid": "metsi a hydraulic",
    "brake calipers": "dicaliper tsa breeki",
    "calipers": "dicaliper",
    "wheel cylinders": "disilinda tsa wheel",
    "brake discs": "didiski tsa breeki",
    "discs": "didiski",
    "brake drums": "didrum tsa breeki",
    "drums": "didrum",
    "anti-lock system": "ABS system",
    "ABS": "ABS",
    "steering": "go laola",
    "steering wheel": "steering wheel",
    "steering rack": "steering rack",
    "power steering": "power steering",
    "suspension": "go emisa",
    "springs": "dispring",
    "shock absorbers": "dishock absorber",
    "struts": "distrut",
    "battery": "bateri",
    "car battery": "bateri ya koloi",
    "alternator": "alternator",
    "fan belt": "belt ya fan",
    "drive belt": "belt ya go tlhanya",
    "radiator": "radiator",
    "coolant": "metsi a go pholosa",
    "thermostat": "thermostat",
    "overheating": "go futhafutha thata",
    "exhaust": "mofufutso",
    "exhaust pipe": "pipe ya mofufutso",
    "catalytic converter": "catalytic converter",
    "muffler": "silencer",
    "tailpipe": "pipe ya mofufutso",
    "wheels": "mabono",
    "tyres": "matayara",
    "tires": "matayara",
    "tyre pressure": "kgatelelo ya tayara",
    "spare wheel": "wheel ya tshwaragano",
    "spare tyre": "tayara ya tshwaragano",
    "fuel tank": "tanka ya petrol",
    "petrol tank": "tanka ya petrol",
    "petrol": "petrol",
    "diesel": "diesel",
    "fuel pump": "pampu ya petrol",
    "fuel filter": "sefa sa petrol",
    "fuel gauge": "geyiji ya petrol",
    "dashboard": "dashboard",
    "speedometer": "speedometer",
    "tachometer": "tachometer",
    "rev counter": "rev counter",
    "warning lamps": "mabone a tlhokomelo",
    "warning lights": "mabone a tlhokomelo",
    "oil pressure": "kgatelelo ya oli",
    "low oil pressure": "kgatelelo ya oli e kwa tlase",
    "oil filter": "sefa sa oli",
    "engine oil": "oli ya enjini",
    "drivetrain": "tsamaiso ya go tlhanya",
    "torque": "torque",
    "revolutions per minute": "RPM",
    "RPM": "RPM",
    "refuelling": "go tshela petrol",
    "petrol station": "gesi",
    "garage": "garage",
    "workshop": "workshop",
    "mechanic": "motho wa dikoloi",
    "panel beater": "motho wa panel",
    "breakdown": "koloi e senyegile",
    "car broke down": "koloi e senyegile",
    "tow-in": "go goga",
    "tow truck": "lori ya go goga",
    "bonnet": "deksel ya enjini",
    "hood": "deksel ya enjini",
    "boot": "trunk",
    "trunk": "trunk",
    "indicators": "ma-indicator",
    "turn signals": "ma-indicator",
    "headlights": "mabone a fa pele",
    "headlamps": "mabone a fa pele",
    "fog lights": "mabone a leru",
    "rearview mirror": "seipone sa morago",
    "side mirror": "seipone sa lehlakoreng",
    "windscreen": "windscreen",
    "carburettor": "carburettor",
    "carburetor": "carburetor",
    "spark plugs": "dspark plug",
    "ignition": "go tshuba",
    "air filter": "sefa sa moya",
    "air conditioning": "aircon",
    "aircon": "aircon",
    "hub": "hub",
    "axle": "axle",
    "wheel hub": "hub ya wheel",
    "passenger car": "koloi ya batho",
    "car": "koloi",
    "motor car": "koloi",
    "centre console": "centre console",
    "cup holder": "sebaka sa kompu",
    "seat belt": "belt ya go dula",
    "seatbelt": "belt ya go dula",
    "hazard lights": "mabone a tlhokomelo",
    "hooter": "hooter",
    "horn": "hooter",
    "pedals": "dipedala",
    "accelerator": "accelerator",
    "accelerator pedal": "pedala ya accelerator",
    "footwell": "lefelo la meno",
    "sun visor": "sun visor",
    "rear seat": "setulo sa morago",
    "front seat": "setulo sa pele",
    "back seat": "setulo sa morago",
    "infotainment": "infotainment",
    "car radio": "redio ya koloi",
    "car stereo": "stereo ya koloi",
    "key fob": "key fob",
    "ignition key": "key ya go tshuba",
    "steering column": "kolomu ya steering",
    "floor mat": "carpet fa tlase",
    "ashtray": "seroto sa mogare",
    "odometer": "odometer",
    "trip meter": "trip meter",
    "traffic light": "robot",
    "traffic lights": "marobot",
    "pickup truck": "bakkie",
    "pick-up": "bakkie",
    "ute": "bakkie",
    "minibus taxi": "tekisi",
    "taxi rank": "rank ya ditekesi",
    "road": "tsela",
    "the road": "tsela",
    "highway": "highway",
    "freeway": "highway",
    "just now": "gongwe fela",
    "now now": "gongwe jalo",
    "later": "morago",
    "is it?": "ne?",
    "isn't it?": "ne?",
    "sharp": "sharp",
    "cool": "go monate",
    "awesome": "go monate thata",
    "mate": "tsala ya me",
    "dude": "rre",
    "hey": "heyi",
    "what's up": "o tsogile jang?",
    "ag shame": "eish",
    "shame": "eish",
    "braai": "braai",
    "barbecue": "braai",
    "sosatie": "sosati",
    "jol": "go jola",
    "party": "paty",
    "eish": "eish",
    "yoh": "yoh",
    "ja nee": "ee nnyaa",
    "yes no": "ee nnyaa",
    "no ways": "nnyaa fela",
    "shot": "ke a leboga",
    "thanks": "ke a leboga",
    "thank you": "ke a leboga",
    "please": "ke kopa",
    "sorry": "ke kopa tshwarelo",
    "excuse me": "ke kopa tshwarelo",
    "township": "lokishi",
    "suburb": "suburb",
    "flat": "fulethi",
    "apartment": "fulethi",
    "cellphone": "cellphone",
    "mobile phone": "cellphone",
    "load shedding": "go tima motlakase",
    "power cut": "go tima motlakase",
    "robot": "robot",
    "cheers": "pholo",
    "drink": "go nwa",
    "hangover": "serata",
    "hang out": "go kopana",
    "chill": "go iketla",
    "student": "moithuti",
    "campus": "kampase",
    "lecture": "thuto",
    "exam": "tekanyetso",
    "test": "tekanyetso",
    "Gauteng": "Gauteng",
    "Cape Town": "Kapa",
    "Joburg": "Joburg",
    "Johannesburg": "Johannesburg",
    "Durban": "Theku",
    "Pretoria": "Pitoli",
    "my china": "china ya me",
    "china": "china",
    "bru": "rre",
    "cuz": "kgalana",
    "cousin": "kgalana",
    "auntie": "mmangwane",
    "uncle": "malome",
    "grandmother": "kgokgo",
    "grandfather": "ntatekgolo",
    "now": "gongwe",
    "quick": "ka bonako",
    "fast": "ka bonako",
    "slow": "butututlhe",
    "stop": "ema",
    "go": "tsamaya",
    "wait": "leta",
    "hurry": "bonako",
    "money": "madi",
    "cash": "madi",
    "expensive": "go biza",
    "cheap": "go pholola",
    "food": "dijo",
    "takeaway": "takeaway",
    "takeaways": "ditakeaway",
    "Pistons and Crankshaft": "Dipiston le Crankshaft",
    "Brakes": "Dibreki",
    "faults": "diphoso",
    "Engine": "Enjini",
    "Transmission": "Gearbox",
    "Steering": "Go laola",
    "Suspension": "Go emisa",
    "Battery and Alternator": "Bateri le Alternator",
    "Radiator and Cooling": "Radiator le go pholosa",
    "Exhaust": "Mofufutso",
    "Wheels and Tyres": "Mabono le matayara",
    "Fuel Tank": "Tanka ya petrol",
    "Dashboard Instruments": "Dimetri tsa dashboard",
    "Windscreen Wipers and Cabin Storage": "Ma-wiper le lepono la dashboard",
    "indicate faults such as": "bontsha diphoso tse di swana le",
}

# Sesotho — Free State/Lesotho urban + garage register
ST: dict[str, str] = {
    "Hello there": "Dumela ntate",
    "How are you?": "O phela jwang?",
    "That's great": "Ho monate",
    "Nice one": "Sharp",
    "Yes, exactly": "Ee, hantle",
    "Brother": "Ntate",
    "In a little while": "Hanyane feela",
    "Get lost": "Tsamaea",
    "What a pity": "Eish, joalo",
    "Really?": "Ka nnete?",
    "cubbyhole": "lepono la dashboard",
    "glove compartment": "lepono la dashboard",
    "glove box": "lepono la dashboard",
    "windshield wipers": "ma-wiper",
    "windscreen wipers": "ma-wiper",
    "piston": "piston",
    "pistons": "lipiston",
    "brakes": "libreki",
    "brake": "breeki",
    "engine": "enjini",
    "the engine": "enjini",
    "internal combustion": "ho cheha ka hare",
    "crankshaft": "crankshaft",
    "connecting rod": "connecting rod",
    "cylinder": "silinda",
    "cylinders": "lisilinda",
    "four-stroke cycle": "four-stroke cycle",
    "transmission": "gearbox",
    "gearbox": "gearbox",
    "manual transmission": "gearbox ea seatla",
    "automatic transmission": "auto gearbox",
    "clutch": "clutch",
    "gear lever": "gear lever",
    "gear stick": "gear stick",
    "brake system": "tsamaiso ea libreki",
    "brake pedal": "pedala ea breeki",
    "handbrake": "handbrake",
    "parking brake": "handbrake",
    "hydraulic fluid": "metsi a hydraulic",
    "brake calipers": "licaliper tsa breeki",
    "calipers": "licaliper",
    "wheel cylinders": "lisilinda tsa wheel",
    "brake discs": "lidisiki tsa breeki",
    "discs": "lidisiki",
    "brake drums": "lidrums tsa breeki",
    "drums": "lidrums",
    "anti-lock system": "ABS system",
    "ABS": "ABS",
    "steering": "ho laola",
    "steering wheel": "steering wheel",
    "steering rack": "steering rack",
    "power steering": "power steering",
    "suspension": "ho emisa",
    "springs": "lispring",
    "shock absorbers": "lishock absorber",
    "struts": "listrut",
    "battery": "betri",
    "car battery": "betri ea koloi",
    "alternator": "alternator",
    "fan belt": "belt ea fan",
    "drive belt": "belt ea ho tlhahisa",
    "radiator": "radiator",
    "coolant": "metsi a ho futhumatsa",
    "thermostat": "thermostat",
    "overheating": "ho futhumala haholo",
    "exhaust": "mofufutso",
    "exhaust pipe": "pipe ea mofufutso",
    "catalytic converter": "catalytic converter",
    "muffler": "silencer",
    "tailpipe": "pipe ea mofufutso",
    "wheels": "mabili",
    "tyres": "matayara",
    "tires": "matayara",
    "tyre pressure": "khatello ea tayara",
    "spare wheel": "wheel ea tshoarong",
    "spare tyre": "tayara ea tshoarong",
    "fuel tank": "tanka ea petrol",
    "petrol tank": "tanka ea petrol",
    "petrol": "petrol",
    "diesel": "diesel",
    "fuel pump": "pampu ea petrol",
    "fuel filter": "sefa sa petrol",
    "fuel gauge": "geyiji ea petrol",
    "dashboard": "dashboard",
    "speedometer": "speedometer",
    "tachometer": "tachometer",
    "rev counter": "rev counter",
    "warning lamps": "mabone a temoso",
    "warning lights": "mabone a temoso",
    "oil pressure": "khatello ea oli",
    "low oil pressure": "khatello ea oli e tlase",
    "oil filter": "sefa sa oli",
    "engine oil": "oli ea enjini",
    "drivetrain": "tsamaiso ea ho tlhahisa",
    "torque": "torque",
    "revolutions per minute": "RPM",
    "RPM": "RPM",
    "refuelling": "ho tshela petrol",
    "petrol station": "gesi",
    "garage": "garage",
    "workshop": "workshop",
    "mechanic": "motho ea likoloi",
    "panel beater": "motho ea panel",
    "breakdown": "koloi e senyehile",
    "car broke down": "koloi e senyehile",
    "tow-in": "ho hula",
    "tow truck": "lori ea ho hula",
    "bonnet": "deksel ea enjini",
    "hood": "deksel ea enjini",
    "boot": "trunk",
    "trunk": "trunk",
    "indicators": "ma-indicator",
    "turn signals": "ma-indicator",
    "headlights": "mabone a pele",
    "headlamps": "mabone a pele",
    "fog lights": "mabone a leru",
    "rearview mirror": "seipone sa morao",
    "side mirror": "seipone sa lehlakoreng",
    "windscreen": "windscreen",
    "carburettor": "carburettor",
    "carburetor": "carburetor",
    "spark plugs": "lispark plug",
    "ignition": "ho tshuba",
    "air filter": "sefa sa moea",
    "air conditioning": "aircon",
    "aircon": "aircon",
    "hub": "hub",
    "axle": "axle",
    "wheel hub": "hub ea wheel",
    "passenger car": "koloi ea batho",
    "car": "koloi",
    "motor car": "koloi",
    "centre console": "centre console",
    "cup holder": "sebaka sa kompu",
    "seat belt": "belt ea ho dula",
    "seatbelt": "belt ea ho dula",
    "hazard lights": "mabone a temoso",
    "hooter": "hooter",
    "horn": "hooter",
    "pedals": "lipedala",
    "accelerator": "accelerator",
    "accelerator pedal": "pedala ea accelerator",
    "footwell": "lefelo la maoto",
    "sun visor": "sun visor",
    "rear seat": "setulo sa morao",
    "front seat": "setulo sa pele",
    "back seat": "setulo sa morao",
    "infotainment": "infotainment",
    "car radio": "redio ea koloi",
    "car stereo": "stereo ea koloi",
    "key fob": "key fob",
    "ignition key": "key ea ho tshuba",
    "steering column": "kolomu ea steering",
    "floor mat": "carpet tlaseng",
    "ashtray": "seroto sa mogare",
    "odometer": "odometer",
    "trip meter": "trip meter",
    "traffic light": "robot",
    "traffic lights": "marobot",
    "pickup truck": "bakkie",
    "pick-up": "bakkie",
    "ute": "bakkie",
    "minibus taxi": "tekisi",
    "taxi rank": "rank ea ditekesi",
    "road": "tsela",
    "the road": "tsela",
    "highway": "highway",
    "freeway": "highway",
    "just now": "hanyane feela",
    "now now": "hona joale",
    "later": "hamorao",
    "is it?": "ne?",
    "isn't it?": "ne?",
    "sharp": "sharp",
    "cool": "ho monate",
    "awesome": "ho monate haholo",
    "mate": "motswalle wa ka",
    "dude": "ntate",
    "hey": "heyi",
    "what's up": "o phela jwang?",
    "ag shame": "eish",
    "shame": "eish",
    "braai": "braai",
    "barbecue": "braai",
    "sosatie": "sosati",
    "jol": "ho jola",
    "party": "paty",
    "eish": "eish",
    "yoh": "yoh",
    "ja nee": "ee tjhe",
    "yes no": "ee tjhe",
    "no ways": "tjhe feela",
    "shot": "ke a leboha",
    "thanks": "ke a leboha",
    "thank you": "ke a leboha",
    "please": "ke kopa",
    "sorry": "ke kopa tshwarelo",
    "excuse me": "ke kopa tshwarelo",
    "township": "lokishi",
    "suburb": "suburb",
    "flat": "fulethi",
    "apartment": "fulethi",
    "cellphone": "cellphone",
    "mobile phone": "cellphone",
    "load shedding": "ho tima motlakase",
    "power cut": "ho tima motlakase",
    "robot": "robot",
    "cheers": "pholo",
    "drink": "ho noa",
    "hangover": "serata",
    "hang out": "ho kopana",
    "chill": "ho iketla",
    "student": "moithuti",
    "campus": "kampase",
    "lecture": "thuto",
    "exam": "tekanyetso",
    "test": "tekanyetso",
    "Gauteng": "Gauteng",
    "Cape Town": "Kapa",
    "Joburg": "Joburg",
    "Johannesburg": "Johannesburg",
    "Durban": "Theku",
    "Pretoria": "Pitoli",
    "my china": "china ea ka",
    "china": "china",
    "bru": "ntate",
    "cuz": "kgalana",
    "cousin": "kgalana",
    "auntie": "mmangwane",
    "uncle": "malome",
    "grandmother": "nkgono",
    "grandfather": "ntatekgolo",
    "now": "hona joale",
    "quick": "ka potlako",
    "fast": "ka potlako",
    "slow": "butle",
    "stop": "ema",
    "go": "tsamaea",
    "wait": "leta",
    "hurry": "potlako",
    "money": "chelete",
    "cash": "chelete",
    "expensive": "e boholo",
    "cheap": "e pholileng",
    "food": "lijo",
    "takeaway": "takeaway",
    "takeaways": "litakeaway",
    "Pistons and Crankshaft": "Lipiston le Crankshaft",
    "Brakes": "Libreki",
    "faults": "liphoso",
    "Engine": "Enjini",
    "Transmission": "Gearbox",
    "Steering": "Ho laola",
    "Suspension": "Ho emisa",
    "Battery and Alternator": "Betri le Alternator",
    "Radiator and Cooling": "Radiator le ho futhumatsa",
    "Exhaust": "Mofufutso",
    "Wheels and Tyres": "Mabili le matayara",
    "Fuel Tank": "Tanka ea petrol",
    "Dashboard Instruments": "Dimethara tsa dashboard",
    "Windscreen Wipers and Cabin Storage": "Ma-wiper le lepono la dashboard",
    "indicate faults such as": "bontsha liphoso tse tshoanang le",
}

# Swahili — East African urban + automotive
SW: dict[str, str] = {
    "Hello there": "Habari yako",
    "How are you?": "Habari yako?",
    "That's great": "Vizuri sana",
    "Nice one": "Poa",
    "Yes, exactly": "Ndiyo, haswa",
    "Brother": "Kaka",
    "In a little while": "Kidogo tu",
    "Get lost": "Nenda zako",
    "What a pity": "Pole sana",
    "Really?": "Kweli?",
    "cubbyhole": "sanduku la dashbodi",
    "glove compartment": "sanduku la dashbodi",
    "glove box": "sanduku la dashbodi",
    "windshield wipers": "vipwiper vya windshield",
    "windscreen wipers": "vipwiper vya windscreen",
    "piston": "piston",
    "pistons": "piston",
    "brakes": "breki",
    "brake": "breeki",
    "engine": "injini",
    "the engine": "injini",
    "internal combustion": "mchomo wa ndani",
    "crankshaft": "crankshaft",
    "connecting rod": "connecting rod",
    "cylinder": "silinda",
    "cylinders": "silinda",
    "four-stroke cycle": "mzigo wa stroke nne",
    "transmission": "gearbox",
    "gearbox": "gearbox",
    "manual transmission": "gearbox ya mkono",
    "automatic transmission": "gearbox ya otomatiki",
    "clutch": "clutch",
    "gear lever": "leva ya gia",
    "gear stick": "fimbo ya gia",
    "brake system": "mfumo wa breki",
    "brake pedal": "pedali ya breki",
    "handbrake": "handbrake",
    "parking brake": "handbrake",
    "hydraulic fluid": "maji ya hydraulic",
    "brake calipers": "caliper za breki",
    "calipers": "caliper",
    "wheel cylinders": "silinda za gurudumu",
    "brake discs": "diski za breki",
    "discs": "diski",
    "brake drums": "drum za breki",
    "drums": "drum",
    "anti-lock system": "mfumo wa ABS",
    "ABS": "ABS",
    "steering": "usimamizi",
    "steering wheel": "usimamizi wa gurudumu",
    "steering rack": "steering rack",
    "power steering": "power steering",
    "suspension": "mfumo wa suspension",
    "springs": "springs",
    "shock absorbers": "shock absorber",
    "struts": "strut",
    "battery": "betri",
    "car battery": "betri ya gari",
    "alternator": "alternator",
    "fan belt": "belti ya feni",
    "drive belt": "belti ya kuendesha",
    "radiator": "radiator",
    "coolant": "maji ya baridi",
    "thermostat": "thermostat",
    "overheating": "kupata joto kupita kiasi",
    "exhaust": "moshi wa kutoka",
    "exhaust pipe": "bomba la moshi",
    "catalytic converter": "catalytic converter",
    "muffler": "silencer",
    "tailpipe": "bomba la moshi",
    "wheels": "magurudumu",
    "tyres": "taiya",
    "tires": "taiya",
    "tyre pressure": "shinikizo la taiya",
    "spare wheel": "gurudumu la akiba",
    "spare tyre": "taiya ya akiba",
    "fuel tank": "tanki la mafuta",
    "petrol tank": "tanki la petroli",
    "petrol": "petroli",
    "diesel": "dieseli",
    "fuel pump": "pampu ya mafuta",
    "fuel filter": "kichujio cha mafuta",
    "fuel gauge": "geji ya mafuta",
    "dashboard": "dashbodi",
    "speedometer": "spidomita",
    "tachometer": "tachometer",
    "rev counter": "kipima mzigo",
    "warning lamps": "taa za onyo",
    "warning lights": "taa za onyo",
    "oil pressure": "shinikizo la mafuta",
    "low oil pressure": "shinikizo la mafuta chini",
    "oil filter": "kichujio cha mafuta",
    "engine oil": "mafuta ya injini",
    "drivetrain": "mfumo wa kuendesha",
    "torque": "torque",
    "revolutions per minute": "RPM",
    "RPM": "RPM",
    "refuelling": "kuongeza mafuta",
    "petrol station": "stesheni ya mafuta",
    "garage": "garaji",
    "workshop": "karakana",
    "mechanic": "fundi wa magari",
    "panel beater": "fundi wa paneli",
    "breakdown": "gari kuvunjika",
    "car broke down": "gari imevunjika",
    "tow-in": "kuvuta",
    "tow truck": "lori ya kuvuta",
    "bonnet": "boneti",
    "hood": "boneti",
    "boot": "buti",
    "trunk": "buti",
    "indicators": "indicator",
    "turn signals": "indicator",
    "headlights": "taa za mbele",
    "headlamps": "taa za mbele",
    "fog lights": "taa za ukungu",
    "rearview mirror": "kioo cha nyuma",
    "side mirror": "kioo cha upande",
    "windscreen": "windscreen",
    "carburettor": "carburettor",
    "carburetor": "carburetor",
    "spark plugs": "spark plug",
    "ignition": "kuwasha",
    "air filter": "kichujio cha hewa",
    "air conditioning": "aircon",
    "aircon": "aircon",
    "hub": "hub",
    "axle": "axle",
    "wheel hub": "hub ya gurudumu",
    "passenger car": "gari la abiria",
    "car": "gari",
    "motor car": "gari",
    "centre console": "dashbodi ya kati",
    "cup holder": "mshikaji wa kikombe",
    "seat belt": "belti ya kiti",
    "seatbelt": "belti ya kiti",
    "hazard lights": "taa za hatari",
    "hooter": "honii",
    "horn": "honii",
    "pedals": "pedali",
    "accelerator": "accelerator",
    "accelerator pedal": "pedali ya kasi",
    "footwell": "eneo la miguu",
    "sun visor": "kivuli cha jua",
    "rear seat": "kiti cha nyuma",
    "front seat": "kiti cha mbele",
    "back seat": "kiti cha nyuma",
    "infotainment": "infotainment",
    "car radio": "redio ya gari",
    "car stereo": "stereo ya gari",
    "key fob": "key fob",
    "ignition key": "ufunguo wa kuwasha",
    "steering column": "kolamu ya usimamizi",
    "floor mat": "mkeka wa sakafu",
    "ashtray": "bakuli la sigara",
    "odometer": "odometer",
    "trip meter": "kipima safari",
    "traffic light": "taa za barabarani",
    "traffic lights": "taa za barabarani",
    "pickup truck": "pickup",
    "pick-up": "pickup",
    "ute": "pickup",
    "minibus taxi": "daladala",
    "taxi rank": "kituo cha daladala",
    "road": "barabara",
    "the road": "barabara",
    "highway": "barabara kuu",
    "freeway": "barabara kuu",
    "just now": "sasa hivi",
    "now now": "sasa hivi",
    "later": "baadaye",
    "is it?": "sivyo?",
    "isn't it?": "sivyo?",
    "sharp": "poa",
    "cool": "poa",
    "awesome": "poa sana",
    "mate": "rafiki",
    "dude": "kaka",
    "hey": "heyi",
    "what's up": "mambo vipi?",
    "ag shame": "pole",
    "shame": "pole",
    "braai": "braai",
    "barbecue": "braai",
    "sosatie": "mshikaki",
    "jol": "kucheza",
    "party": "sherehe",
    "eish": "eish",
    "yoh": "yoh",
    "ja nee": "ndiyo hapana",
    "yes no": "ndiyo hapana",
    "no ways": "hapana kabisa",
    "shot": "asante",
    "thanks": "asante",
    "thank you": "asante",
    "please": "tafadhali",
    "sorry": "samahani",
    "excuse me": "samahani",
    "township": "mtaa",
    "suburb": "kitongoji",
    "flat": "fleti",
    "apartment": "fleti",
    "cellphone": "simu",
    "mobile phone": "simu",
    "load shedding": "kukatwa umeme",
    "power cut": "kukatwa umeme",
    "robot": "taa za barabarani",
    "cheers": "maisha marefu",
    "drink": "kunywa",
    "hangover": "kichwa cha kulaumiwa",
    "hang out": "kutembea",
    "chill": "kupumzika",
    "student": "mwanafunzi",
    "campus": "kampasi",
    "lecture": "mhadhara",
    "exam": "mtihani",
    "test": "mtihani",
    "Gauteng": "Gauteng",
    "Cape Town": "Kapa",
    "Joburg": "Joburg",
    "Johannesburg": "Johannesburg",
    "Durban": "Durban",
    "Pretoria": "Pretoria",
    "my china": "china yangu",
    "china": "china",
    "bru": "kaka",
    "cuz": "binamu",
    "cousin": "binamu",
    "auntie": "shangazi",
    "uncle": "mjomba",
    "grandmother": "nyanya",
    "grandfather": "babu",
    "now": "sasa",
    "quick": "haraka",
    "fast": "haraka",
    "slow": "polepole",
    "stop": "simama",
    "go": "enda",
    "wait": "subiri",
    "hurry": "haraka",
    "money": "pesa",
    "cash": "pesa",
    "expensive": "ghali",
    "cheap": "rahisi",
    "food": "chakula",
    "takeaway": "takeaway",
    "takeaways": "takeaway",
    "Pistons and Crankshaft": "Piston na Crankshaft",
    "Brakes": "Breki",
    "faults": "hitilafu",
    "Engine": "Injini",
    "Transmission": "Gearbox",
    "Steering": "Usimamizi",
    "Suspension": "Suspension",
    "Battery and Alternator": "Betri na Alternator",
    "Radiator and Cooling": "Radiator na kupoa",
    "Exhaust": "Moshi wa kutoka",
    "Wheels and Tyres": "Magurudumu na taiya",
    "Fuel Tank": "Tanki la mafuta",
    "Dashboard Instruments": "Vipimo vya dashbodi",
    "Windscreen Wipers and Cabin Storage": "Vipwiper na sanduku la dashbodi",
    "indicate faults such as": "onyesha hitilafu kama",
}

LANG_TABLES: dict[str, dict[str, str]] = {
    "zu": ZU,
    "xh": XH,
    "tn": TN,
    "st": ST,
    "sw": SW,
}

# Register overlays: AI formal/literary → urban garage register (source_lang = lang in build)
ZU_REGISTER: list[dict] = [
    {"original": "Sawubona, ngiyajabula ukukubona.", "fix": "Sawubona mfowethu, kunjani?", "temp_min": 0.65, "contributor": "Arjuna Badger Press corpus — register overlay"},
    {"original": "Ngiyacela ukuthi ungikhumbule.", "fix": "Ngicela ungikhumbule, bhuti.", "temp_min": 0.65},
    {"original": "amabrembo", "fix": "amabreki", "temp_min": 0.75},
    {"original": "Amabrembo", "fix": "Amabreki", "temp_min": 0.75},
    {"original": "amabhuleki", "fix": "amabreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Amabhuleki", "fix": "Amabreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ibhuleki", "fix": "ibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ebhuleki", "fix": "ebreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "yebhuleki", "fix": "yebreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "kwebhuleki", "fix": "kwebreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ibhreki", "fix": "ibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "i-ibhreki", "fix": "i-ibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "lebhuleki", "fix": "lebhreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ipedali lebhuleki", "fix": "ipepedi lebhreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "yebreki", "fix": "yamabreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "isigqivini", "fix": "ipiston", "temp_min": 0.75},
    {"original": "Isigqivini", "fix": "Ipiston", "temp_min": 0.75},
    {"original": "isivinini sesivinini", "fix": "isivinini", "temp_min": 0.75},
    {"original": "ibhokisi lokugcina", "fix": "ibhokisi le-dashboard", "temp_min": 0.9},
    {"original": "Ibhokisi lokugcina", "fix": "Ibhokisi le-dashboard", "temp_min": 0.9},
    {"original": "umshini wemoto", "fix": "umshini wegaraji", "temp_min": 0.9},
    {"original": "Umshini wemoto", "fix": "Umshini wegaraji", "temp_min": 0.9},
    {"original": "ukuphuka kwemoto", "fix": "imoto yaphuka", "temp_min": 0.9},
    {"original": "Imoto yami yaphuleka.", "fix": "Imoto yami yaphuka, bhuti.", "temp_min": 0.9},
    {"original": "Ngidinga ukugcwalisa ipetrol.", "fix": "Ngidinga ukuya egesi.", "temp_min": 0.9},
    {"original": "Amabreki awasebenzi.", "fix": "Amabreki awasebenzi, sharp.", "temp_min": 0.9},
    {"original": "ipaneel", "fix": "idashboard", "temp_min": 0.9},
    {"original": "Ipaneel", "fix": "Idashboard", "temp_min": 0.9},
    {"original": "umkhuhlane wemoto", "fix": "umkhuhlane", "temp_min": 0.75},
    {"original": "isixhobo sokulawula", "fix": "i-steering wheel", "temp_min": 0.75},
    {"original": "Isixhobo sokulawula", "fix": "I-steering wheel", "temp_min": 0.75},
    {"original": "wipers", "fix": "ama-wiper", "temp_min": 0.65, "source_url": "https://www.motorpress.co.za/"},
    {"original": "Wipers", "fix": "Ama-wiper", "temp_min": 0.65, "source_url": "https://www.motorpress.co.za/"},
    {"original": "amaphutha emoto", "fix": "izinkinga", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ikhombisa amaphutha njenge", "fix": "ikhombisa izinkinga njenge", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Ngiyajabula kakhulu.", "fix": "Kuhle kakhulu, sharp.", "temp_min": 0.75, "source_url": "https://www.africanstorybook.org/", "weight": 20, "contributor": "Arjuna Badger Press — African Storybook register (curated)"},
]

XH_REGISTER: list[dict] = [
    {"original": "Molo, ndiyavuya ukukubona.", "fix": "Molo bhuti, kunjani?", "temp_min": 0.65},
    {"original": "Ndingumntu othanda ukunceda abanye.", "fix": "Ndimntu onothando lokunceda abanye.", "temp_min": 0.65},
    {"original": "iibrembo", "fix": "iibhreki", "temp_min": 0.75},
    {"original": "Iibrembo", "fix": "Iibhreki", "temp_min": 0.75},
    {"original": "isixhobo sokujonga", "fix": "i-steering wheel", "temp_min": 0.75},
    {"original": "Isixhobo sokujonga", "fix": "I-steering wheel", "temp_min": 0.75},
    {"original": "isigqibini", "fix": "ipiston", "temp_min": 0.75},
    {"original": "Isigqibini", "fix": "Ipiston", "temp_min": 0.75},
    {"original": "ibhokisi lokugcina", "fix": "ibhokisi le-dashboard", "temp_min": 0.9},
    {"original": "Ibhokisi lokugcina", "fix": "Ibhokisi le-dashboard", "temp_min": 0.9},
    {"original": "umqhubi wemoto", "fix": "umqhubi wegaraji", "temp_min": 0.9},
    {"original": "Imoto yam yaphukile.", "fix": "Imoto yam yaphuka, bhuti.", "temp_min": 0.9},
    {"original": "Ndidinga ipetrol.", "fix": "Ndidinga ukuya egesi.", "temp_min": 0.9},
    {"original": "Iibhreki azisebenzi.", "fix": "Iibhreki azisebenzi, sharp.", "temp_min": 0.9},
    {"original": "ipanele", "fix": "idashboard", "temp_min": 0.9},
    {"original": "Ipanele", "fix": "Idashboard", "temp_min": 0.9},
    {"original": "iilights zangaphambili", "fix": "iilights zangaphambili", "temp_min": 0.0, "temp_max": 0.5},
    {"original": "wipers", "fix": "ama-wiper", "temp_min": 0.65, "source_url": "https://www.motorpress.co.za/"},
    {"original": "Wipers", "fix": "Ama-wiper", "temp_min": 0.65, "source_url": "https://www.motorpress.co.za/"},
    {"original": "iimpazamo zemoto", "fix": "iingxaki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "ibonisa iimpazamo njenge", "fix": "ibonisa iingxaki njenge", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Ndiyavuya kakhulu.", "fix": "Kuhle, sharp sharp.", "temp_min": 0.75, "source_url": "https://archive.org/details/XHOOLD_DBS_HS", "weight": 20, "contributor": "Arjuna Badger Press — Xhosa literary register (curated)"},
]

TN_REGISTER: list[dict] = [
    {"original": "Dumela, ke itumetse go go bona.", "fix": "Dumela rre, o tsogile jang?", "temp_min": 0.65},
    {"original": "Ke kopa gore o nkgopole.", "fix": "Ke kopa o nkgopole, tsala.", "temp_min": 0.65},
    {"original": "dibremo", "fix": "dibreki", "temp_min": 0.75},
    {"original": "Dibremo", "fix": "Dibreki", "temp_min": 0.75},
    {"original": "diporeke", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Diporeke", "fix": "Dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "porekepetlele", "fix": "pedala ya dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "poreke", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Diborake", "fix": "Dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "diborake", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "borake", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Sistimi ya borake", "fix": "Sistimi ya dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Diberekhe", "fix": "Dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "diberekhe", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "berekhe", "fix": "dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "berekhe pedal", "fix": "pedala ya dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "le bidiwang cubbyhole", "fix": "le bidiwang jalo", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "cubbyhole", "fix": "lepono la dashboard", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "setirring wheel", "fix": "steering wheel", "temp_min": 0.75},
    {"original": "Setirring wheel", "fix": "Steering wheel", "temp_min": 0.75},
    {"original": "motho wa dikoloi", "fix": "motho wa garage", "temp_min": 0.9},
    {"original": "Motho wa dikoloi", "fix": "Motho wa garage", "temp_min": 0.9},
    {"original": "koloi e senyegile", "fix": "koloi e kgaogile", "temp_min": 0.9},
    {"original": "Ke tlhoka petrol.", "fix": "Ke tlhoka go tshela egasing.", "temp_min": 0.9},
    {"original": "Dibreki ga di a bereka.", "fix": "Dibreki ga di a bereka, sharp.", "temp_min": 0.9},
    {"original": "paneelbord", "fix": "dashboard", "temp_min": 0.9},
    {"original": "Paneelbord", "fix": "Dashboard", "temp_min": 0.9},
    {"original": "wisselstroomwekker", "fix": "alternator", "temp_min": 0.9},
    {"original": "Wisselstroomwekker", "fix": "Alternator", "temp_min": 0.9},
    {"original": "transmissie", "fix": "gearbox", "temp_min": 0.9},
    {"original": "Transmissie", "fix": "Gearbox", "temp_min": 0.9},
    {"original": "fobakkie", "fix": "diphoso", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "bontsha fobakkie jaaka", "fix": "bontsha diphoso jaaka", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "pedala ya breeki", "fix": "pedala ya dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "brake pressure", "fix": "kgatelelo ya dibreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "owner's manual", "fix": "buku ya mong wa koloi", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Ke itumetse thata.", "fix": "Ke a leboga, sharp.", "temp_min": 0.75, "source_url": "https://www.africanstorybook.org/", "weight": 20, "contributor": "Arjuna Badger Press — Setswana Storybook register (curated)"},
]

ST_REGISTER: list[dict] = [
    {"original": "Dumela, ke thabela ho u bona.", "fix": "Dumela ntate, o phela jwang?", "temp_min": 0.65},
    {"original": "Ke kopa hore o nkhopole.", "fix": "Ke kopa o nkhopole, motswalle.", "temp_min": 0.65},
    {"original": "libremo", "fix": "libreki", "temp_min": 0.75},
    {"original": "Libremo", "fix": "Libreki", "temp_min": 0.75},
    {"original": "difere", "fix": "libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Difere", "fix": "Libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "breeki", "fix": "libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Li-brake", "fix": "Libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "li-brake", "fix": "libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "le bitsoang cubbyhole", "fix": "le bitsoang jalo", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Sistimi ea brake", "fix": "Sistimi ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "brake pressure", "fix": "khatello ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "sistimi ea brake", "fix": "sistimi ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "pedala ea breeki", "fix": "pedala ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "le bitswang cubbyhole", "fix": "le bitswang jalo", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "cubbyhole", "fix": "lepono la dashboard", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "owner's manual", "fix": "buka ea motsamaisi", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "motho ea likoloi", "fix": "motho ea garage", "temp_min": 0.9},
    {"original": "Motho ea likoloi", "fix": "Motho ea garage", "temp_min": 0.9},
    {"original": "koloi e senyehile", "fix": "koloi e khaohile", "temp_min": 0.9},
    {"original": "Ke hloka petrol.", "fix": "Ke hloka ho tshela egasing.", "temp_min": 0.9},
    {"original": "Libreki ha li sebetse.", "fix": "Libreki ha li sebetse, sharp.", "temp_min": 0.9},
    {"original": "paneelbord", "fix": "dashboard", "temp_min": 0.9},
    {"original": "Paneelbord", "fix": "Dashboard", "temp_min": 0.9},
    {"original": "wisselstroomwekker", "fix": "alternator", "temp_min": 0.9},
    {"original": "Wisselstroomwekker", "fix": "Alternator", "temp_min": 0.9},
    {"original": "transmissie", "fix": "gearbox", "temp_min": 0.9},
    {"original": "Transmissie", "fix": "Gearbox", "temp_min": 0.9},
    {"original": "setirring wheel", "fix": "steering wheel", "temp_min": 0.75},
    {"original": "Setirring wheel", "fix": "Steering wheel", "temp_min": 0.75},
    {"original": "fobakkie", "fix": "liphoso", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "bontsha fobakkie joalo ka", "fix": "bontsha liphoso joalo ka", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "brake system", "fix": "tsamaiso ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "mathata a brake system", "fix": "mathata a tsamaiso ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "breeki system", "fix": "tsamaiso ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "libreki system", "fix": "tsamaiso ea libreki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Ke thabela haholo.", "fix": "Ke a leboha, sharp.", "temp_min": 0.75, "source_url": "https://emandulo.apc.uct.ac.za/metadata/FHYA%20Depot/1188/7130/index.html", "weight": 20, "contributor": "Arjuna Badger Press — Sekese register (curated)"},
]

SW_REGISTER: list[dict] = [
    {"original": "Habari, ninafurahi kukuona.", "fix": "Mambo vipi kaka?", "temp_min": 0.65},
    {"original": "breki za gari", "fix": "breki", "temp_min": 0.75},
    {"original": "Breki za gari", "fix": "Breki", "temp_min": 0.75},
    {"original": "gurudumu la kuendesha", "fix": "steering wheel", "temp_min": 0.75},
    {"original": "Gurudumu la kuendesha", "fix": "Steering wheel", "temp_min": 0.75},
    {"original": "sanduku la kuweka", "fix": "sanduku la dashbodi", "temp_min": 0.9},
    {"original": "Sanduku la kuweka", "fix": "Sanduku la dashbodi", "temp_min": 0.9},
    {"original": "fundishaji wa magari", "fix": "fundishaji wa garaji", "temp_min": 0.9},
    {"original": "Gari langu limevunjika.", "fix": "Gari langu limekataa, kaka.", "temp_min": 0.9},
    {"original": "Ninahitaji petroli.", "fix": "Ninahitaji kwenda stesheni.", "temp_min": 0.9},
    {"original": "Breki hazifanyi kazi.", "fix": "Breki hazifanyi kazi, poa tu.", "temp_min": 0.9},
    {"original": "dashibodi", "fix": "dashbodi", "temp_min": 0.9},
    {"original": "Dashibodi", "fix": "Dashbodi", "temp_min": 0.9},
    {"original": "mfumo wa kutoa moshi", "fix": "moshi wa kutoka", "temp_min": 0.75},
    {"original": "Mfumo wa kutoa moshi", "fix": "Moshi wa kutoka", "temp_min": 0.75},
    {"original": "makosa ya gari", "fix": "hitilafu", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "inaonyesha makosa kama", "fix": "inaonyesha hitilafu kama", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — car handbook register guard"},
    {"original": "Ninafurahi sana.", "fix": "Poa sana, kaka.", "temp_min": 0.75, "source_url": "https://wikisource.org/wiki/Swahili_Tales", "weight": 20, "contributor": "Arjuna Badger Press — Swahili Tales register (curated)"},
]

# Curated literary-sourced translate rows (human-reviewed; not bulk-mined)
ZU_LITERARY: list[dict] = [
    {"original": "Once upon a time", "fix": "Kudala-dala", "temp_min": 0.0, "temp_max": 0.5, "weight": 20, "source_url": "https://archive.org/details/cu31924026950968", "contributor": "Arjuna Badger Press — Callaway Izinganekwane (curated)"},
    {"original": "the tortoise", "fix": "ufudu", "temp_min": 0.0, "temp_max": 0.5, "weight": 20, "source_url": "https://archive.org/details/cu31924026950968", "contributor": "Arjuna Badger Press — Callaway Izinganekwane (curated)"},
    {"original": "the hare", "fix": "unogwaja", "temp_min": 0.0, "temp_max": 0.5, "weight": 20, "source_url": "https://archive.org/details/cu31924026950968", "contributor": "Arjuna Badger Press — Callaway Izinganekwane (curated)"},
]

LANG_REGISTER: dict[str, list[dict]] = {
    "zu": ZU_REGISTER,
    "xh": XH_REGISTER,
    "tn": TN_REGISTER,
    "st": ST_REGISTER,
    "sw": SW_REGISTER,
}

# Swahili urban seed (priority over AF-template rows where originals differ)
SW_SEED: list[dict] = [
    {"original": "Hello", "fix": "Habari", "source_url": "https://en.wiktionary.org/wiki/habari", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Yes", "fix": "Ndiyo", "source_url": "https://en.wiktionary.org/wiki/ndiyo", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "No", "fix": "Hapana", "source_url": "https://en.wiktionary.org/wiki/hapana", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "What's up?", "fix": "Mambo vipi?", "source_url": "https://en.wiktionary.org/wiki/mambo", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "OK", "fix": "Sawa sawa", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Cool", "fix": "Poa", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Thank you", "fix": "Asante", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Sorry", "fix": "Pole", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Come on", "fix": "Twende", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Shut up", "fix": "Nyamaza", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Money", "fix": "Pesa", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Food", "fix": "Chakula", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Friend", "fix": "Rafiki", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "How are you?", "fix": "Habari yako?", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Goodbye", "fix": "Kwaheri", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Really?", "fix": "Kweli?", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Good morning", "fix": "Habari za asubuhi", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Brother", "fix": "Kaka", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Sister", "fix": "Dada", "contributor": "Arjuna Badger Press corpus seed"},
    {"original": "Now", "fix": "Sasa", "contributor": "Arjuna Badger Press corpus seed"},
]

# Swahili-only extras not in AF template
SW_EXTRA: list[dict] = [
    {"original": "matatu", "fix": "daladala", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — East Africa register"},
    {"original": "boda boda", "fix": "pikipiki", "temp_min": 0.75, "contributor": "Arjuna Badger Press corpus — East Africa register"},
    {"original": "petrol station attendant", "fix": "mtu wa stesheni", "temp_min": 0.75},
    {"original": "flat tyre", "fix": "taiya imepata pancha", "temp_min": 0.75},
    {"original": "puncture", "fix": "pancha", "temp_min": 0.75},
]
